### ISSUE TITLE
Normalize REST Interface

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/simulation-service#43]
The endpoints need to be refactored so that they will match the CIEMSS service.
Specifically, the refactor will target [this OpenAPI spec](https://github.com/DARPA-ASKEM/simulation-service/files/11671048/updated_swagger.json.txt).

With these changes, new operations will now have to be manually included.

### TODOs being done in #45 
- [ ] Create epoch handler
- [x] Update acceptable problem inputs
- [x] Normalize job status responses
- [x] Refactor `/calls/simulate` into `/simulate`
- [x] Refactor `/calls/calibrate` into `/calibrate`
- [x] Add dummy `/ensemble` endpoint

**Comment by anandijain** [comment]
I'm reading through this now, and the ensemble endpoint doesn't seem to have a reference to any datasets to fit the collection of models to. Could I get an example payload for each of the endpoints to test against? cc @brandomr

**Comment by brandomr** [comment]
@anandijain i think we were expecting that the model configurations sent for ensembling would be "pre" calibrated. But we did consider having a mapping where one model configuration maps to 1 dataset--is that ever reasonable to do? E.g. calibrate various models to different datasets prior to calibration?
