### ISSUE TITLE
Incorporate new workflow

### ISSUE THREAD

**Issue by fivegrant** [DARPA-ASKEM/simulation-service#44]
There needs to be some refactoring to handle the changes to TDS and workflow designs.

### TODOs
- [ ] Run simulate(s) upon calibration completion
- [ ] Write job status to TDS
- [ ] (requires TDS coordination) Use presigned handle provided by TDS on complete to write to S3 

The new flow: 
![image](https://github.com/DARPA-ASKEM/simulation-service/assets/14170067/7135ea97-f375-4984-be20-81d9f926dd6e)
